spring:
  application:
    name: messages-assignment
server:
  port: 8080

logging:
  level:
    ROOT: INFO
    com.example: INFO

externalserver:
  url: http://localhost:8181/mock_external_service
scheduler:
  cron: 0 0 23 * * *
  zone: Europe/Amsterdam